version: "3"
services:
  gateway:
    container_name: externr.mor.local
    build: ./nginx
    volumes:
      - ./nginx/nginx-default.development.conf:/etc/nginx/conf.d/default.conf
      - ./media:/media
    depends_on:
      externr_app:
        condition: service_started
    ports:
      - 8008:8008
    networks:
      - mor_bridge_network
    env_file:
      - .env.local
  externr_app:
    build: ./app
    env_file:
      - .env.local
    volumes:
      - ./media:/media
      - ./app:/app
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
    networks:
      - externr_network
      - mor_bridge_network
    command: ["bash", "/app/deploy/docker-entrypoint.development.sh"]
    restart: always

  database:
    image: postgres:16
    shm_size: '1024m'
    ports:
      - "5432"
    env_file:
      - .env.local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - externr_network

  redis:
    image: redis
    networks:
      - externr_network
    ports:
      - "6379"

  app_celery_worker:
    build: ./app
    command: "celery -A config worker -l info"
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./media:/media
    env_file:
      - .env.local
    networks:
      - externr_network
      - mor_bridge_network

  app_celery_beat:
    build: ./app
    command: "celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./media:/media
    env_file:
      - .env.local
    networks:
      - externr_network
      - mor_bridge_network


volumes:
  postgres-data:

networks:
  externr_network:
    external: true
  mor_bridge_network:
    external: true
