# Generated by Django 3.2.18 on 2024-05-16 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0011_auto_20240514_1454"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaakDeellink",
        ),
    ]
