# Generated by Django 3.2.18 on 2024-06-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0012_delete_taakdeellink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taaktype",
            name="externe_instantie_email",
        ),
        migrations.RemoveField(
            model_name="taaktype",
            name="externe_instantie_feedback_vereist",
        ),
        migrations.RemoveField(
            model_name="taaktype",
            name="externe_instantie_naam",
        ),
        migrations.RemoveField(
            model_name="taaktype",
            name="externe_instantie_naam_verantwoordelijke",
        ),
        migrations.AddField(
            model_name="taak",
            name="bezig_met_verwerken",
            field=models.BooleanField(default=False),
        ),
    ]
