# Generated by Django 4.2.11 on 2024-06-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0013_auto_20240618_1202"),
    ]

    operations = [
        migrations.AddField(
            model_name="taaktype",
            name="externe_instantie",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="externe_instantie_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="externe_instantie_verantwoordelijke",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
