# Generated by Django 4.2.11 on 2024-06-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0014_taaktype_externe_instantie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taaktype",
            name="externe_instantie",
            field=models.CharField(default="Externe instantie", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="taaktype",
            name="externe_instantie_email",
            field=models.EmailField(default="j.strikwerda@alteza.nl", max_length=254),
            preserve_default=False,
        ),
    ]
