# Generated by Django 4.2.11 on 2024-07-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0016_taakgebeurtenis_resolutie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taakstatus",
            name="naam",
            field=models.CharField(
                choices=[
                    ("nieuw", "Nieuw"),
                    ("toegewezen", "Toegewezen"),
                    ("openstaand", "Openstaand"),
                    ("voltooid", "Voltooid"),
                    ("voltooid_met_feedback", "Voltooid met feedback"),
                ],
                default="nieuw",
                max_length=50,
            ),
        ),
    ]
