# Generated by Django 4.2.15 on 2025-04-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0017_alter_taakstatus_naam"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakgebeurtenis",
            name="notificatie_verstuurd",
            field=models.BooleanField(default=True),
        ),
    ]
