# Generated by Django 4.2.15 on 2025-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0018_taakgebeurtenis_notificatie_verstuurd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taak",
            name="bericht",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="taak",
            name="titel",
            field=models.CharField(max_length=200),
        ),
    ]
