# Generated by Django 4.2.15 on 2025-05-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0019_alter_taak_bericht_alter_taak_titel"),
    ]

    operations = [
        migrations.AddField(
            model_name="taak",
            name="verwijderd_op",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
