# Generated by Django 4.2.15 on 2025-05-26 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0021_afzenderemailadres_taaktype_afzender_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taaktype",
            name="afzender_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taaktypes_voor_afzenderemailadres",
                to="taken.afzenderemailadres",
            ),
        ),
    ]
