# Generated by Django 4.2.15 on 2025-05-27 12:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0022_alter_taaktype_afzender_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="afzenderemailadres",
            name="wijken",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=list, size=None
            ),
        ),
    ]
