# Generated by Django 4.2.15 on 2025-11-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0023_afzenderemailadres_wijken"),
    ]

    operations = [
        migrations.AddField(
            model_name="taaktype",
            name="standaard_omschrijving_intern",
            field=models.CharField(
                blank=True,
                default="Automatich voltooid door ExternR",
                max_length=5000,
                null=True,
            ),
        ),
    ]
