# Generated by Django 4.2.15 on 2025-11-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0024_taaktype_standaard_omschrijving_intern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taaktype",
            name="standaard_omschrijving_intern",
            field=models.CharField(
                blank=True,
                default="Automatisch voltooid door ExternR",
                max_length=5000,
                null=True,
            ),
        ),
    ]
