# Generated by Django 4.2.15 on 2025-04-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticatie", "0003_gebruiker_telefoonnummer"),
    ]

    operations = [
        migrations.AddField(
            model_name="gebruiker",
            name="verwijderd_op",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
